#server:
#  port: 8383
#
#spring:
#  datasource:
#    url: jdbc:mysql://10.14.36.20:3546/dipam-dms
#    username: sankesh
#    password: PassWord@123
#
#
#
#
## JWT TOKEN KEY AND ITS EXPIRATION
#application:
#  security:
#    jwt:
#      secret-key: 4bb6d1dfbafb64a681139d1586b6f1160d18159afd57c8c79136d7490630407c
#      access-token-expiration: 10800000 #3 HOURS TOKEN Expired
#      #      access-token-expiration: 86400000
#      refresh-token-expiration: 604800000
##      refresh-token-expiration: 60
#
##=================== END ================================================#
#
#
## ################### REGISTER WITH EUREKA SERVER ################### #
#eureka:
#  client:
#    service-url:
#      defaultZone: http://10.10.108.26:8181/DMSEurekaRegistry/eureka
#
#
## ################### LOGGER  ################### #
#logging:
#  file:
#    name: /APP/Dipam_Documents/DMS_LOGS/authService/authService.log  # Path to the custom log file
#  level:
#    root: INFO              # Set the default logging level
#    com.utiitsl.DMSAUTHSERVICE: DEBUG  # Set specific logging level for your package
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"  # Console log format
#    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"     # File log format
#
## ################### END  ################### #
#
## ################### DM REDIRECT URL  ################### #
#dms:
#  redirect-url:
#    ui: http://10.10.108.26:8181/dipam-dms/auth/callback
#    error: http://10.10.108.26:8181/dipam-dms/errorPage
#
## ################### END  ################### #
#
## ################### PARICHAY IMPLEMENTATION  ################### #
#parichay:
#  client-issuer-url: https://parichay.staging.nic.in/pnv1/oauth2/authorize
#  serviceId: SAtCRcmPonDM5YBifC2reXvevQhokTut
#  clientSecret: PonfhjVRK3cjs49KHWHacdeThRu1hSgh
#  client-redirect-uri: http://103.208.56.61:8282/dipamDms/authService/api/v1/auth/redirect-url-dms
#  #  client-redirect-uri: http://10.10.108.26:8282/diauthService/api/v1/auth/redirect-url-dms
#  client-authorization-grant-type: authorization_code
#  client-scope: user_details
#  client-codeChallengeMethod: S256
#  client-State: dev
#  request-token-api: https://parichay.nic.in/pnv1/salt/api/oauth2/token
#  request-userDetails: https://parichay.staging.nic.in/pnv1/salt/api/oauth2/userdetails
#
## ################### END  ################### #
#
##  parichay.client-issuer-url=https://parichay.nic.in/pnv1/oauth2/authorize
##  parichay.client-id=Lsb5YBifC2reXvevQZB6hokgzqPunHik
##  parichay.client-secret=onfhjURK3cjs49KHWHacdMSTBzRu1hMn
##  parichay.client-redirect-uri=https://www.dipam.gov.in/ddaservice/usrauth
##  parichay.client-authorization-grant-type=authorization_code
##  parichay.client-scope=user_details
##  parichay.client-codeChallengeMethod=S256
##  parichay.client-State=Prod
#
#
#openapi:
#  service:
#    title: auth-service doc
#    version: 1.0.0
#    url: http://103.208.56.61:8282
#
#springdoc:
#  api-docs:
#    path: /v3/api-docs
#  swagger-ui:
#    path: /swagger-ui.html